/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "src/rosettastone/server/templates/**/*.html",
    "src/rosettastone/server/api/migrations.py",
  ],
  theme: {
    extend: {
      colors: {
        "on-error": "#690005",
        "on-secondary-fixed-variant": "#3b4b36",
        "error-container": "#93000a",
        "on-secondary-fixed": "#101f0d",
        "on-tertiary-fixed-variant": "#614018",
        "on-primary-fixed-variant": "#7a2f1e",
        "secondary-container": "#3d4d38",
        "surface-variant": "#353535",
        "surface-container-low": "#1c1b1b",
        "error": "#ffb4ab",
        "on-primary-container": "#531205",
        "tertiary-container": "#b4885a",
        "surface-bright": "#393939",
        "on-primary-fixed": "#3d0600",
        "tertiary-fixed-dim": "#efbd8a",
        "inverse-on-surface": "#313030",
        "on-surface-variant": "#dbc1bb",
        "on-primary": "#5c190a",
        "surface": "#131313",
        "secondary-fixed": "#d5e8cb",
        "primary-fixed-dim": "#ffb4a3",
        "primary-fixed": "#ffdad2",
        "on-tertiary-fixed": "#2c1700",
        "surface-tint": "#ffb4a3",
        "on-error-container": "#ffdad6",
        "on-secondary": "#253421",
        "surface-container-lowest": "#0e0e0e",
        "on-surface": "#e5e2e1",
        "tertiary-fixed": "#ffdcbc",
        "background": "#131313",
        "secondary-fixed-dim": "#b9ccb0",
        "surface-container-highest": "#353535",
        "on-secondary-container": "#abbea2",
        "secondary": "#b9ccb0",
        "surface-dim": "#131313",
        "tertiary": "#efbd8a",
        "on-tertiary": "#472a03",
        "primary": "#ffb4a3",
        "outline": "#a38c86",
        "inverse-surface": "#e5e2e1",
        "surface-container": "#20201f",
        "on-background": "#e5e2e1",
        "on-tertiary-container": "#3f2300",
        "inverse-primary": "#984633",
        "primary-container": "#d67660",
        "outline-variant": "#55433e",
        "surface-container-high": "#2a2a2a",
        "success": "#8B9D83",
        "warn": "#D4A373",
        "terracotta": "#D4745E",
        "sage": "#8B9D83",
        "gold": "#D4A574",
        "critical": "#D85650",
      },
      fontFamily: {
        headline: ["Inter"],
        body: ["Inter"],
        label: ["JetBrains Mono"],
        mono: ["JetBrains Mono"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
