"""initial_schema

Revision ID: 7f21b03d2b42
Revises:
Create Date: 2026-04-07 21:56:23.743175

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7f21b03d2b42'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('details_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dataset_generation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('dataset_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tuning_cost_usd', sa.Float(), nullable=False),
    sa.Column('production_cost_usd', sa.Float(), nullable=False),
    sa.Column('total_cost_usd', sa.Float(), nullable=False),
    sa.Column('pairs_generated', sa.Integer(), nullable=False),
    sa.Column('output_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('migrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('optimized_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('baseline_score', sa.Float(), nullable=True),
    sa.Column('improvement', sa.Float(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('recommendation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('recommendation_reasoning', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_latency_p50', sa.Float(), nullable=True),
    sa.Column('source_latency_p95', sa.Float(), nullable=True),
    sa.Column('target_latency_p50', sa.Float(), nullable=True),
    sa.Column('target_latency_p95', sa.Float(), nullable=True),
    sa.Column('projected_source_cost_per_call', sa.Float(), nullable=True),
    sa.Column('projected_target_cost_per_call', sa.Float(), nullable=True),
    sa.Column('config_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('per_type_scores_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('warnings_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('safety_warnings_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('checkpoint_stage', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('checkpoint_data_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('current_stage', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stage_progress', sa.Float(), nullable=True),
    sa.Column('overall_progress', sa.Float(), nullable=True),
    sa.Column('max_cost_usd', sa.Float(), nullable=True),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('token_breakdown_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column(
        'optimization_score_history_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False
    ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pipelines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('config_yaml', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('overall_progress', sa.Float(), nullable=True),
    sa.Column('current_module', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registered_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('registered_models', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_registered_models_model_id'), ['model_id'], unique=True
        )

    op.create_table('task_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('payload_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('worker_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('correlation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_name'), ['name'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('api_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_api_key'), ['api_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('migration_id', sa.Integer(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('metadata_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['migration_id'], ['migrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approval_workflows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('migration_id', sa.Integer(), nullable=False),
    sa.Column('required_approvals', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['migration_id'], ['migrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approval_workflows', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_approval_workflows_migration_id'), ['migration_id'], unique=True
        )

    op.create_table('gepa_iterations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('migration_id', sa.Integer(), nullable=False),
    sa.Column('iteration', sa.Integer(), nullable=False),
    sa.Column('total_iterations', sa.Integer(), nullable=False),
    sa.Column('mean_score', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['migration_id'], ['migrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gepa_iterations', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_gepa_iterations_migration_id'), ['migration_id'], unique=False
        )

    op.create_table('migration_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('migration_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('snapshot_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('optimized_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['migration_id'], ['migrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('migration_versions', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_migration_versions_migration_id'), ['migration_id'], unique=False
        )

    op.create_table('pipeline_stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_id', sa.Integer(), nullable=False),
    sa.Column('module_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('optimized_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pipeline_stages', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_pipeline_stages_pipeline_id'), ['pipeline_id'], unique=False
        )

    op.create_table('team_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('team_memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_memberships_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_memberships_user_id'), ['user_id'], unique=False)

    op.create_table('test_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('migration_id', sa.Integer(), nullable=False),
    sa.Column('phase', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('output_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('composite_score', sa.Float(), nullable=False),
    sa.Column('is_win', sa.Boolean(), nullable=False),
    sa.Column('scores_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('details_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('response_length', sa.Integer(), nullable=False),
    sa.Column('new_response_length', sa.Integer(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('new_token_count', sa.Integer(), nullable=True),
    sa.Column('evaluators_used', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fallback_triggered', sa.Boolean(), nullable=False),
    sa.Column('prompt_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('response_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('new_response_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('failure_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['migration_id'], ['migrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('monthly_limit_usd', sa.Float(), nullable=False),
    sa.Column('current_month_spend_usd', sa.Float(), nullable=False),
    sa.Column('budget_month', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('warnings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('migration_id', sa.Integer(), nullable=False),
    sa.Column('warning_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['migration_id'], ['migrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ab_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('migration_id', sa.Integer(), nullable=False),
    sa.Column('version_a_id', sa.Integer(), nullable=False),
    sa.Column('version_b_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('traffic_split', sa.Float(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('winner', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['migration_id'], ['migrations.id'], ),
    sa.ForeignKeyConstraint(['version_a_id'], ['migration_versions.id'], ),
    sa.ForeignKeyConstraint(['version_b_id'], ['migration_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ab_tests', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_ab_tests_migration_id'), ['migration_id'], unique=False
        )

    op.create_table('annotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('migration_id', sa.Integer(), nullable=False),
    sa.Column('test_case_id', sa.Integer(), nullable=True),
    sa.Column('annotator_id', sa.Integer(), nullable=True),
    sa.Column('annotation_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['annotator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['migration_id'], ['migrations.id'], ),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('annotations', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_annotations_migration_id'), ['migration_id'], unique=False
        )

    op.create_table('approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('decision', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['approval_workflows.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_id', 'user_id', name='uq_approval_workflow_user')
    )
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approvals_workflow_id'), ['workflow_id'], unique=False)

    op.create_table('ab_test_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ab_test_id', sa.Integer(), nullable=False),
    sa.Column('test_case_id', sa.Integer(), nullable=True),
    sa.Column('assigned_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('score_a', sa.Float(), nullable=True),
    sa.Column('score_b', sa.Float(), nullable=True),
    sa.Column('winner', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('details_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ab_test_id'], ['ab_tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ab_test_results', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_ab_test_results_ab_test_id'), ['ab_test_id'], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ab_test_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ab_test_results_ab_test_id'))

    op.drop_table('ab_test_results')
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approvals_workflow_id'))

    op.drop_table('approvals')
    with op.batch_alter_table('annotations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_annotations_migration_id'))

    op.drop_table('annotations')
    with op.batch_alter_table('ab_tests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ab_tests_migration_id'))

    op.drop_table('ab_tests')
    op.drop_table('warnings')
    op.drop_table('user_budgets')
    op.drop_table('test_cases')
    with op.batch_alter_table('team_memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_memberships_user_id'))
        batch_op.drop_index(batch_op.f('ix_team_memberships_team_id'))

    op.drop_table('team_memberships')
    with op.batch_alter_table('pipeline_stages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pipeline_stages_pipeline_id'))

    op.drop_table('pipeline_stages')
    with op.batch_alter_table('migration_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_migration_versions_migration_id'))

    op.drop_table('migration_versions')
    with op.batch_alter_table('gepa_iterations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gepa_iterations_migration_id'))

    op.drop_table('gepa_iterations')
    with op.batch_alter_table('approval_workflows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_workflows_migration_id'))

    op.drop_table('approval_workflows')
    op.drop_table('alerts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_api_key'))

    op.drop_table('users')
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_name'))

    op.drop_table('teams')
    op.drop_table('task_queue')
    with op.batch_alter_table('registered_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registered_models_model_id'))

    op.drop_table('registered_models')
    op.drop_table('pipelines')
    op.drop_table('migrations')
    op.drop_table('dataset_generation_runs')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
